version: '3'

# run in foreground: `docker-compose up`
# run in background: `docker-compose up -d`
# stop in background: `docker-compose down`
# reset the db: `docker-compose down -v && docker-compose build`

services:
  db:
    image: mongo:4.4
    ports:
    - 27017:27017
    volumes:
    - db-data:/data/db

volumes:
  db-data:
