---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakebook-notifications-api
  labels:
    app: fakebook-notifications
    role: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakebook-notifications
      role: api
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fakebook-notifications
        role: api
    spec:
      containers:
      - name: api
        image: fakebook.azurecr.io/fakebooknotifications:latest
        ports:
        - containerPort: 80
        env:
        - name: NotificationsDatabaseSettings__ConnectionString
          value: 'mongodb://fakebook-notifications-db'
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakebook-notifications-db
  labels:
    app: fakebook-notifications
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakebook-notifications
      role: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fakebook-notifications
        role: db
    spec:
      containers:
      - name: db
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: db-volume
          subPath: data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: fakebook-notifications
