---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fakebook-notifications
  labels:
    app: fakebook-notifications
    role: db
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
